image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

stages:
  - Base
  - Variants

before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

### MANAGE HELM CHARTS ###
"Check Helm":
  stage: Base
  image: docker.aquaveo.com/it/helm-docker:0.1.0
  before_script: []
  script:
    - check_helm_chart helm/condor-manager
  except:
   - tags
   - master

"Update Helm":
  stage: Base
  image: docker.aquaveo.com/it/helm-docker:0.1.0
  before_script: []
  script:
    - check_helm_chart helm/condor-manager --upload
  only: 
    - master

### BUILD ###
"Build (Base)":
  stage: Base
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile 
        --destination $CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG-dev
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache
  except:
   - tags

"Build (Collector)":
  stage: Variants
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile.collector 
        --destination $CI_REGISTRY_IMAGE/condor-collector:$CI_COMMIT_REF_SLUG-dev
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG-dev
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache
  except:
   - tags

"Build (Scheduler)":
  stage: Variants
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile.scheduler 
        --destination $CI_REGISTRY_IMAGE/condor-scheduler:$CI_COMMIT_REF_SLUG-dev
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG-dev
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache
  except:
   - tags

"Build (Worker)":
  stage: Variants
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile.worker 
        --destination $CI_REGISTRY_IMAGE/condor-worker:$CI_COMMIT_REF_SLUG-dev
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG-dev
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache
  except:
   - tags

"Build (Standalone)":
  stage: Variants
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile.standalone 
        --destination $CI_REGISTRY_IMAGE/condor-standalone:$CI_COMMIT_REF_SLUG-dev
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG-dev
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache
  except:
   - tags

### PASSWORD GENERATOR ###

"Build (htcpassgen)":
  stage: Base
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR/htcpassgen
        --dockerfile $CI_PROJECT_DIR/htcpassgen/Dockerfile 
        --destination $CI_REGISTRY_IMAGE/htcpassgen:latest
        --cache=true
        --cache-repo CI_REGISTRY_IMAGE/cache
  only:
   - master

### BUILD AND PUSH ###
"Build and Push (Base)":
  stage: Base
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile 
        --destination $CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG
        --destination $CI_REGISTRY_IMAGE/condor-base:latest
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache
  only:
   - tags

"Build and Push (Collector)":
  stage: Variants
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile.collector
        --destination $CI_REGISTRY_IMAGE/condor-collector:$CI_COMMIT_TAG
        --destination $CI_REGISTRY_IMAGE/condor-collector:latest
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache
  only:
   - tags

"Build and Push (Scheduler)":
  stage: Variants
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile.scheduler 
        --destination $CI_REGISTRY_IMAGE/condor-scheduler:$CI_COMMIT_TAG
        --destination $CI_REGISTRY_IMAGE/condor-scheduler:latest
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache
  only:
   - tags

"Build and Push (Worker)":
  stage: Variants
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile.worker 
        --destination $CI_REGISTRY_IMAGE/condor-worker:$CI_COMMIT_TAG
        --destination $CI_REGISTRY_IMAGE/condor-worker:latest
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache
  only:
   - tags

"Build and Push (Standalone)":
  stage: Variants
  script:
    - /kaniko/executor 
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile.standalone 
        --destination $CI_REGISTRY_IMAGE/condor-standalone:$CI_COMMIT_TAG
        --destination $CI_REGISTRY_IMAGE/condor-standalone:latest
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/condor-base:$CI_COMMIT_REF_SLUG
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache
  only:
   - tags
