FROM ubuntu:24.04

# Install HTCondor
RUN apt-get update -qq \
 && apt-get -yqq install wget gnupg2 supervisor > /dev/null \
 && mkdir -p /var/log/supervisor \
 && wget -qO - https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-24.x-Key | gpg --dearmour -o /etc/apt/trusted.gpg.d/condor.gpg \
 && echo "deb https://research.cs.wisc.edu/htcondor/repo/ubuntu/24.x noble main" >> /etc/apt/sources.list \
 && apt-get update -qq \
 && apt search condor \
 && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -yqq minicondor=24.9.2-1+ubu24 > /dev/null \
 && rm -rf /var/lib/apt/lists/*

# Set up config files
COPY docker-entrypoint.sh /
COPY conf/condor_config.local /etc/condor/
COPY conf/supervisord.conf /etc/supervisor/
COPY conf/supervisor.d/condor.conf /etc/supervisor/conf.d/

ENV _CONDOR_DESIGNATED_PROJECT="TEST"
ENV JOB_DEFAULT_REQUESTMEMORY=128
CMD "/docker-entrypoint.sh"
