ARG BASE_IMAGE=aquaveollc/condor-base:24.9.2-1_u24.04
FROM $BASE_IMAGE

# Tethys needs to be able to ssh into the scheduler
RUN apt-get update -qq > /dev/null \ 
 && apt-get install -qq -y openssh-server > /dev/null \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -p /run/sshd \
 && mkdir -p /var/lib/condor/.ssh \
 && chown condor /var/lib/condor/.ssh \
 && chmod 700 /var/lib/condor/.ssh \
 && mkdir -p /home/submituser/.ssh \
 && chown submituser /home/submituser/.ssh \
 && chmod 700 /home/submituser/.ssh \
 && usermod -s /bin/bash condor

# Set up config files
COPY conf/condor.d/00-standalone /etc/condor/config.d/
COPY conf/supervisor.d/sshd.conf /etc/supervisor/conf.d/

# Add liveness check
COPY htcondor-schedd-liveness /usr/local/bin/
