FROM ubuntu:24.04

# Install HTCondor
RUN apt-get update -qq \
 && apt-get -yqq install wget gnupg2 supervisor > /dev/null \
 && mkdir -p /var/log/supervisor \
 && wget -qO - https://research.cs.wisc.edu/htcondor/repo/keys/HTCondor-24.x-Key | gpg --dearmour -o /etc/apt/trusted.gpg.d/condor.gpg \
 && echo "deb https://research.cs.wisc.edu/htcondor/repo/ubuntu/24.x noble main" >> /etc/apt/sources.list \
 && apt-get update -qq \
 && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -yqq condor=24.9.2-1+ubu24 > /dev/null \
 && rm -rf /var/lib/apt/lists/*

# Setup user dirs
RUN useradd -m -s /bin/bash -g condor submituser \
 && chmod g+w /home/submituser \
 && echo "umask 002" >> /home/submituser/.bashrc \
 && echo "umask 002" >> /etc/profile \
 && mkdir -p /var/lib/condor/keys

# Set up config files
COPY docker-entrypoint.sh /
COPY conf/condor_config.local.base /etc/condor/condor_config.local
COPY conf/supervisord.conf /etc/supervisor/
COPY conf/supervisor.d/condor.conf /etc/supervisor/conf.d/

ENV _CONDOR_DESIGNATED_PROJECT="TEST"
ENV JOB_DEFAULT_REQUESTMEMORY=128
CMD ["/docker-entrypoint.sh"]
