apiVersion: apps/v1
kind: Deployment
metadata:
  name: condor-collector
  labels:
    app.kubernetes.io/name: condor-collector
    helm.sh/chart: {{ include "condor-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: condor-collector
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: condor-collector
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.aquaveo.com/tethys/condor/condor-docker/condor-collector:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: _CONDOR_CONDOR_HOST
              value: "condor-collector"
            - name: _CONDOR_SEC_PASSWORD_FILE
              value: "/etc/condor/pool_password/password"
          ports:
            - name: condor
              containerPort: 9618
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: pool-password
              mountPath: /etc/condor/pool_password
      volumes:
        - name: pool-password
          secret:
            defaultMode: 0600
            secretName: condor-pool-password
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
