apiVersion: v1
kind: ConfigMap
metadata:
  name: condor-worker-json
data:
  worker.json: |
    {
      "kind":"Pod",
      "apiVersion":"v1",
      "metadata":{
          "generateName":"condor-worker",
          "namespace":"default",
          "labels":{
            "app":"condor-worker"
          }
      },
      "spec":{
          "volumes":[
            {
                "name":"pool-password",
                "secret":{
                  "secretName":"condor-pool-password",
                  "defaultMode":384
                }
            }
          ],
          "containers":[
            {
                "name":"condor-worker",
                "image":{{.Values.worker.image.repository}}:{{.Values.worker.image.tag}},
                "env":[
                  {
                      "name":"_CONDOR_CONDOR_HOST",
                      "value":"condor-collector"
                  },
                  {
                      "name":"_CONDOR_SEC_PASSWORD_FILE",
                      "value":"/etc/condor/pool_password/password"
                  },
                  {
                      "name":"CONDOR_CPUS",
                      "value":{{.Values.worker.cpus}}
                  },
                  {
                      "name":"CONDOR_MEMORY",
                      "value":{{.Values.worker.memory}}
                  }
                ],
                "resources":{
                  "limits":{
                      "memory":{{.Values.worker.memory_limit}},
                  },
                  "requests":{
                      "cpu":{{.Values.worker.cpus}},
                      "memory":{{.Values.worker.memory}}Mi
                  }
                },
                "volumeMounts":[
                  {
                      "name":"pool-password",
                      "mountPath":"/etc/condor/pool_password"
                  }
                ],
                "imagePullPolicy":"Always"
            }
          ],
          "restartPolicy":"Never"
      }
    }
