apiVersion: apps/v1
kind: Deployment
metadata:
  name: condor-scheduler
  labels:
    app.kubernetes.io/name: condor-scheduler
    helm.sh/chart: {{ include "condor-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: condor-scheduler
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: condor-scheduler
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.aquaveo.com/tethys/condor/condor-docker/condor-scheduler:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: _CONDOR_CONDOR_HOST
              value: "condor-collector"
            - name: _CONDOR_SEC_PASSWORD_FILE
              value: "/etc/condor/pool_password/password"
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
            - name: condor
              containerPort: 9618
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/htcondor-schedd-liveness
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 22
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: pool-password
              mountPath: /etc/condor/pool_password
            - name: condor-authorized-keys
              readOnly: true
              mountPath: /var/lib/condor/keys
      volumes:
        - name: pool-password
          secret:
            defaultMode: 0600
            secretName: condor-pool-password
        - name: condor-authorized-keys
          secret:
            defaultMode: 0600
            secretName: condor-authorized-keys
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
