apiVersion: v1
kind: Service
metadata:
  name: condor-scheduler
  labels:
    app.kubernetes.io/name: condor-scheduler
    helm.sh/chart: {{ include "condor-manager.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: condor-scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
